// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrjrzwndjfvobxcoyspa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyanJ6d25kamZ2b2J4Y295c3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzQ3MTEsImV4cCI6MjA2NjI1MDcxMX0.Rx3FTprLkiHi567g39uFYq3cO1TgLYkpNAnNVvpzH74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);